# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
notifications:
  email: false
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start
matrix:
  allow_failures:
    - os: osx
    - julia: nightly
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("PDMP");include(Pkg.dir("PDMP")*"/test/ci_setup.jl"); Pkg.test("PDMP"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("PDMP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
